import { Tutor } from '../types';
import { v4 as uuidv4 } from 'uuid';

// Заготовленные фотографии для преподавателей
export const tutorPhotos = [
  'images/teacher1.png',
  'images/teacher2.jpg',
  'images/teacher3.jpeg',
  'images/teacher4.jpg',
  'images/teacher5.jpg',
  'images/teacher6.jpg',
  'images/teacher7.png',
  'images/teacher8.png',
  'images/teacher9.png',
];

export const subjects = [
  'Математика',
  'Физика',
  'Химия',
  'Биология',
  'История',
  'Литература',
  'Английский язык',
  'Информатика',
  'География',
  'Обществознание',
];

export const mockTutors: Tutor[] = [
  {
    id: uuidv4(),
    name: 'Анна Смирнова',
    photo: tutorPhotos[0],
    description: 'Преподаю иностранные языки 10 лет. Индивидуальный подход к каждому ученику. Использую современные методики обучения.',
    subjects: ['Английский язык'],
    price: 1500,
    lessonType: 'both',
    phone: '+7 (900) 123-45-67',
  },
  {
    id: uuidv4(),
    name: 'Иван Ежов',
    photo: tutorPhotos[1],
    description: 'Доктор физико-математических наук. Помогаю школьникам и студентам разобраться в сложных темах физики.',
    subjects: ['Физика'],
    price: 2000,
    lessonType: 'online',
    phone: '+7 (900) 234-56-78',
  },
  {
    id: uuidv4(),
    name: 'Виктория Соколова',
    photo: tutorPhotos[2],
    description: 'Школьный учитель по математике с большим стажем. Готовлю к ОГЭ и ЕГЭ',
    subjects: ['Математика'],
    price: 1700,
    lessonType: 'offline',
    phone: '+7 (900) 345-67-89',
  },
  {
    id: uuidv4(),
    name: 'Дмитрий Козлов',
    photo: tutorPhotos[3],
    description: 'Программист с 15-летним стажем. Обучаю основам программирования, веб-разработке, алгоритмам и структурам данных.',
    subjects: ['Информатика'],
    price: 2500,
    lessonType: 'online',
    phone: '+7 (900) 456-78-90',
  },
  {
    id: uuidv4(),
    name: 'Мария Иванова',
    photo: tutorPhotos[4],
    description: 'Биолог-исследователь. Делаю сложные биологические процессы понятными. Помогу подготовиться к экзаменам и поступлению в медицинские вузы.',
    subjects: ['Биология'],
    price: 1800,
    lessonType: 'both',
    phone: '+7 (900) 567-89-01',
  },
  {
    id: uuidv4(),
    name: 'Алексей Николаев',
    photo: tutorPhotos[5],
    description: 'Географ с опытом преподавания 12 лет. Интересно объясняю, использую наглядные материалы и современные методики.',
    subjects: ['География'],
    price: 1900,
    lessonType: 'offline',
    phone: '+7 (900) 678-90-12',
  },
  {
    id: uuidv4(),
    name: 'Ольга Кузнецова',
    photo: tutorPhotos[6],
    description: 'Филолог с красным дипломом. Помогаю влюбиться в литературу, развить навыки анализа текста и правильно писать сочинения.',
    subjects: ['Литература'],
    price: 1600,
    lessonType: 'online',
    phone: '+7 (900) 789-01-23',
  },
  {
    id: uuidv4(),
    name: 'Елена Морозова',
    photo: tutorPhotos[7],
    description: 'Историк, автор методических пособий. Готовлю к экзаменам и олимпиадам. Увлекательные занятия с использованием интерактивных материалов.',
    subjects: ['История', 'Обществознание'],
    price: 2100,
    lessonType: 'both',
    phone: '+7 (900) 890-12-34',
  },
  
  {
    id: uuidv4(),
    name: 'Наталья Волкова',
    photo: tutorPhotos[8],
    description: 'Кандидат химических наук. Преподаю химию с упором на практическое применение знаний и понимание материала.',
    subjects: ['Химия'],
    price: 1400,
    lessonType: 'online',
    phone: '+7 (900) 901-23-45',
  },
];